### ISSUE TITLE
Get valid returns from skyscanner API

### ISSUE THREAD

**Issue by mcook1992** [mcook1992/Project_1#5]
@bingbingma will support

**Comment by mcook1992** [comment]
Can't use live flight data because of cross-domain issues--would need to make a call from a server. However, we can hopefully use historical data from a computer. Teddy and David will investigate whether that works. 

However, there may also be an issue with not having a functioning API key. If that's the case, we'll just use a different API. 

If we can't make it work by 1 HOUR INTO SAT CLASS, we will reevaulte and maybe change API keys.

**Comment by Vertigo-1** [comment]
Fixed this with Jamal using Axios to pass X-Rapid-API key to the URL to return the results we need.  Tested extensively with David.  Have updated and JS file and pushed it to Skyscanner-JS-File branch.
